addReviewers: true
addAssignees: false

reviewers:
  - alexandre-abrioux
  - MantisClone
  - leoslr

# Set 0 to add all the reviewers (default: 0)
numberOfReviewers: 0

skipKeywords:
  - wip
  - draft
